# NumPy exercises

We are going to practice NumPy skills and basic syntax.

We put here also some examples that were not in the tutorial on purpose. Try to use google and offial NumPy documentation to solve these exercises.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
# Assuming "null vector" really means an array of zeros, not actually nulls
nvec = np.zeros((10,))
print(nvec)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [5]:
nvec = np.zeros((10,))
nvec[4] = 1
print(nvec)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [10]:
print(np.arange(10, 50))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [11]:
start = np.arange(10)
result = start[::-1]
print(result)

[9 8 7 6 5 4 3 2 1 0]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [13]:
print(np.arange(9).reshape((3, 3)))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [18]:
arr = np.array([1,2,0,0,4,0])
print(np.flatnonzero(arr))

[0 1 4]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [19]:
print(np.random.rand(3, 3))

[[0.36471446 0.03797047 0.17857281]
 [0.69287934 0.16033288 0.86553173]
 [0.36752388 0.07423965 0.66297376]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [20]:
arr = np.random.rand(3, 3)
print(arr)

print(f"Minimum: {np.min(arr)}")
print(f"Maximum: {np.max(arr)}")

[[0.23974151 0.07511144 0.64994968]
 [0.16354619 0.75125142 0.69644239]
 [0.52486086 0.75654971 0.33675462]]
Minimum: 0.07511143543067555
Maximum: 0.7565497110099494


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [21]:
arr = np.random.rand(30)
print(arr)

print(f"Mean: {np.mean(arr)}")

[0.4860237  0.64881398 0.55897414 0.55173191 0.56897147 0.58055314
 0.11962724 0.18255314 0.20435841 0.69352484 0.47508541 0.5754424
 0.0707912  0.07711272 0.65700458 0.36522721 0.55211989 0.38435429
 0.62850428 0.36282227 0.64819563 0.49543516 0.08450766 0.66339661
 0.26541632 0.29464882 0.17016962 0.27532777 0.86573392 0.00337283]
Mean: 0.41699335123096787


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [23]:
# Lemme just borrow my function from the video real quick
def layers(*nums):
    # Happy path - assuming always at least one arg
    l = len(nums)
    # Initial case
    # arr = np.full((l, l), nums[0]) Every number (layer) except the center is actually 2 rows/columns
    arr = np.full((l * 2 - 1, l * 2 - 1), nums[0])
    for i in range(1, l):
        # Start from the outside
        # arr[i:-1-i, i:-1-i] = nums[i] Exclusive upper bound
        arr[i:-i, i:-i] = nums[i]
    # Actually that might do it
    return arr

print(layers(1, 0, 0))

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [45]:
# This will keep the same amount of dimentions as was input,
# ie a 1d array will have a zero at the front and back,
# a 2d array will be surrounded by zeros on the plane
# a 3d array would be like a cube nested inside a larger cube
#    with zeros in the outer layer
# I don't want to think about a 4d array
def addZeros(arr):
    shape = np.add(arr.shape, 2)
    big = np.zeros(shape)
    big[(slice(1, -1),) * shape.size] = arr
    return big
    
existing = np.ones((3,3))
print(existing)

added = addZeros(existing)
print(added)

print(addZeros(np.ones((2,))))
print(addZeros(np.ones((2,2,2))))
# Fun stuff :3

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]
[0. 1. 1. 0.]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 1. 1. 0.]
  [0. 1. 1. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 1. 1. 0.]
  [0. 1. 1. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [46]:
# Am I supposed to guess without typing these out, or just type them out and that's the answer...?
print(0 * np.nan) # nan
print(np.nan == np.nan) # Could go either way, but I'm leaning more towards false
print(np.inf > np.nan) # Probably not
print(np.nan - np.nan) # nan
print(np.nan in set([np.nan])) # maybe? But again gonna say nope
print(0.3 == 3 * 0.1) # This probably gets caught by how inaccurate pythyon floats are and the multiplication will be something like 0.29999999999999

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [47]:
# Target: [
#   [0 0 0 0 0]
#   [1 0 0 0 0]
#   [0 2 0 0 0]
#   [0 0 3 0 0]
#   [0 0 0 4 0]
# ]

arr = np.zeros((5, 5))
arr[[1, 2, 3, 4], [0, 1, 2, 3]] = [1, 2, 3, 4]
print(arr)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [48]:
# 6 rows
# 7 columns
# 8 layers
# Each row contains a 7x8 slice
# Each row contains 56 items
# x = 1, 44 items remain
# Each column in the row contains 8 items
# y = 44 // 8 = 5, 4 items remain
# z = 4
arr = np.arange(6 * 7 * 8).reshape((6, 7, 8))
print(arr[1, 5, 4])

100


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [55]:
# To normalize a matrix, you divide each element by the determinant of the matrix - https://mathforums.com/threads/how-do-i-normalize-a-matrix.18218/
randMatr = np.random.rand(5, 5)
determinant = np.linalg.det(randMatr)
normalized = randMatr / determinant
print(normalized)

[[15.12131028  2.02836341 23.02154937  4.80863045  2.26216489]
 [14.23346518 39.19853094  6.13098368  3.65371126 15.34240594]
 [23.86266982 30.26662351 27.29603118 20.83030439 23.46561581]
 [35.05507657 28.75907502 32.49725475 35.02037749  3.63018258]
 [19.03877697  3.81002661 34.98624646  9.75955811 38.34810164]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [72]:
def negate(arr, low, high):
    # Inclusive lower bound, exclusive upper bound
    withinThresh = np.flatnonzero((arr >= low) & (arr < high))
    arr[withinThresh] *= -1
        
start = np.array([1, 3, 5, 7, 9])
print(start)
negate(start, 3, 8)
print(start)

[1 3 5 7 9]
[ 1 -3 -5 -7  9]


#### 29. How to round away from zero a float array ? (★☆☆)

In [73]:
def awayFromZero(arr):
    return np.where(arr > 0, np.ceil(arr), np.floor(arr))
    
start = np.arange(-2, 2, 0.5)
print(start)
print(awayFromZero(start))

[-2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5]
[-2. -2. -1. -1.  0.  1.  1.  2.]


#### 30. How to find common values between two arrays? (★☆☆)

In [75]:
# Just list the common values?
arr1 = np.arange(1, 5)
arr2 = np.arange(3, 8)
intersect = np.intersect1d(arr1, arr2)
print(arr1)
print(arr2)
print(intersect)

[1 2 3 4]
[3 4 5 6 7]
[3 4]


#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [79]:
# I imagine the first one probably throws an error, but the second would return with i
print(np.sqrt(-1) == np.emath.sqrt(-1))

# I find it curious that the program continued running, I had expected an exception which would stop the program

False


<ipython-input-79-1ce6481f0d3f>:2: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [83]:
# Do I write said generator function?
def generate(upTo):
    i = 0
    while i < upTo:
        yield i
        i += 1

# It appears the normal np.array() method requires the size to be known immediately,
# not terribly surprising when thinking about it because all elements must be together
# in memory. So without predicting the size you can either convert it to a list first
print(np.array(list(generate(10))))
# or use fromiter
print(np.fromiter(generate(10), int))

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [87]:
# 10 evenly spaced values? Excluding 0 and 1 themselves
step = 1 / 11 # 1 is already excluded, add one to the step divisor so 0 can be skipped
arr = np.arange(step, 1, step)
print(arr)
print(arr.size)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]
10


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [90]:
arr = np.random.rand(10)
arr.sort()
print(arr)

[0.05326368 0.09510945 0.12271279 0.36419098 0.40980593 0.54400267
 0.62800406 0.68290256 0.84983495 0.88060858]


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [92]:
def equal(arr1, arr2):
    return np.array_equal(arr1, arr2)
    
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])
c = np.array([2, 3, 4])
d = np.array([2, 3])

print(equal(a, b)) # True
print(equal(a, c)) # False
print(equal(a, d)) # False

True
False
False


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [93]:
vec = np.random.rand(10)
print(vec)
vec[vec.argmax()] = 0
print(vec)

[0.02155027 0.44327432 0.41724737 0.407479   0.9383592  0.53565785
 0.58773167 0.01017126 0.0196591  0.53062683]
[0.02155027 0.44327432 0.41724737 0.407479   0.         0.53565785
 0.58773167 0.01017126 0.0196591  0.53062683]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [95]:
# Find the value in a vector which is closest to a given value
# ie [1, 3, 6, 8] the closest value to 5 is 6. So return 6
def closest(arr, value):
    differences = np.abs(arr - value)
    return arr[differences.argmin()]
    
vec = np.array([1, 3, 6, 8])
print(closest(vec, 5))

6


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [109]:
# Preserving human-readable values? My initial thought was that the bits themselves
# wouldn't change but the way they were interpreted would, ie 0.5f => 1056964608
# Most solutions seem to attept converting in the arguably more natural way of 1.0f => 1
# This makes sense, that's usually what most people would want

# Very simple solution from https://www.kite.com/python/answers/how-to-convert-the-type-of-a-numpy-array-in-place-in-python
# They claim it's in-place, using copy=False in astype seems to indicate it isn't allocating a new
# array, but that's only on the condition that dtype, order, and subok requirements are met.
# I could check something like id(), which as far as I can tell is the memory location if running
# CPython. It's not clear what id is otherwise. Given that CPython is apparently the default version
# and the version downloaded from python.org I assume that's what I have on my system.
# So considering that the id of the array has changed after the cast, it suggests to me that new
# memory has, in fact, been allocated.
arr = np.arange(10, dtype='float32')
print(arr)
print(id(arr))
arr = arr.astype('int32', copy=False)
print(arr)
print(id(arr))
print()

# According to https://stackoverflow.com/questions/4389517/in-place-type-conversion-of-a-numpy-array
# This behaves more like my initial expectation, where the bit values themselves are left unchanged
# It's also clearly setting values in the same memory location, as changes to one array are reflected
# in the other. As such this method is capable of doing both types of conversion depending on what's
# actually desired in the moment.
arr = np.arange(10, dtype='float32')
print(arr)
iarr = arr.view('int32')
print(iarr)
iarr[:] = arr
print(iarr)
print(arr)

# I just spent like 2 hours on this question, I don't know if I should include this time in the "How 
# long did this section take" box

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
3185980203536
[0 1 2 3 4 5 6 7 8 9]
3185980056560

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[         0 1065353216 1073741824 1077936128 1082130432 1084227584
 1086324736 1088421888 1090519040 1091567616]
[0 1 2 3 4 5 6 7 8 9]
[0.0e+00 1.4e-45 2.8e-45 4.2e-45 5.6e-45 7.0e-45 8.4e-45 9.8e-45 1.1e-44
 1.3e-44]


#### 59. How to sort an array by the nth column? (★★☆)

In [112]:
# Assuming a 2d array specifically
def sortNth(arr, n):
    # Slice out the desired column
    # argsort will return the order of indexes
    return arr[np.argsort(arr[:, n])]
    
arr = np.array([
    [1, 2, 3],
    [2, 3, 1],
    [3, 1, 2]
])
print(arr)
print(sortNth(arr, 1))
print(sortNth(arr, 2))

[[1 2 3]
 [2 3 1]
 [3 1 2]]
[[3 1 2]
 [1 2 3]
 [2 3 1]]
[[2 3 1]
 [3 1 2]
 [1 2 3]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [6]:
# Null columns, aka a column with all 0s
def hasNull(arr):
    return not np.all(arr.any(axis=0))
    
arr1 = np.array([
    [1, 1, 1, 0],
    [0, 0, 1, 1],
    [0, 1, 0, 0]
])
arr2 = np.array([
    [1, 1, 0, 1],
    [0, 0, 0, 1],
    [0, 1, 0, 0]
])
print(hasNull(arr1))
print(hasNull(arr2))

False
True


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [16]:
start = np.array([1, 2, 3, 4, 5], dtype='int32')
# Target: [1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]
print(start)

# Can probably stack horizontally then reshape I suppose
result = np.hstack([
    start.reshape((5, 1)),
    np.zeros((5, 3), dtype='int32')
]).flatten()[:-3]
print(result)

# I like a more generic solution
def interleave(arr, count):
    transposed = arr[:, np.newaxis]
    full = np.hstack([
        transposed,
        np.zeros((arr.size, count), dtype=arr.dtype)
    ])
    return full.flatten()[:-count]
    
print(interleave(start, 2))

[1 2 3 4 5]
[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]
[1 0 0 2 0 0 3 0 0 4 0 0 5]


#### 72. How to swap two rows of an array? (★★★)

In [18]:
# So basically
# From [[1 2] [3 4] [5 6] [7 8]]
# To   [[1 2] [7 8] [5 6] [3 4]]
# would be swapping the 2nd and 4th rows
def swap(arr, r1, r2):
    # arr[r1], arr[r2] = arr[r2], arr[r1] The one-liner doesn't work
    temp = np.copy(arr[r1])
    arr[r1] = arr[r2]
    arr[r2] = temp
    
start = np.arange(1, 9).reshape((4, 2))
print(start)
swap(start, 1, 3)
print(start)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2]
 [7 8]
 [5 6]
 [3 4]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [4]:
# Should this be done on an array of values?
# Just negate a single bool or float, as long as it's in-place?
# Are these supposed to be the same action? Will it not work for say an int?


# So apparently the *intended* solution is to negate an array of booleans, and
# completely separately negate an array of floats. These two have nothing to
# do with each other except you're doing a similar type of action in each case
arr = np.array([True, True, False, False, True, False, False, True])
print(arr)
np.logical_not(arr, out=arr)
print(arr)
print()

# Floats
arr = np.array([1.1, 2.2, -3.3, -4.4, 5.5, -6.6, -7.7, 8.8])
print(arr)
np.negative(arr, out=arr)
print(arr)

[ True  True False False  True False False  True]
[False False  True  True False  True  True False]

[ 1.1  2.2 -3.3 -4.4  5.5 -6.6 -7.7  8.8]
[-1.1 -2.2  3.3  4.4 -5.5  6.6  7.7 -8.8]


#### 83. How to find the most frequent value in an array?

In [9]:
rng = np.random.default_rng()
arr = rng.integers(6, size=10)
print(arr)

unique, counts = np.unique(arr, return_counts=True)
print(unique, counts)
i = counts.argmax()

print(f"Most common value {unique[i]} with {counts[i]} occurrences")

[3 1 0 5 4 4 0 5 0 4]
[0 1 3 4 5] [3 1 1 3 2]
0
Most common value 0 with 3 occurrences


#### 89. How to get the n largest values of an array (★★★)

In [12]:
rng = np.random.default_rng()
arr = rng.integers(100, size=25)
print(arr)

n = 10
sort = np.sort(arr)
print(sort[-n:])
# Make sure arr itself hasn't changed
print(arr)

[ 6 26 95 35 25 87 74 93 36 78 76 67  0 21 71 36 85 74 13 75 93 73 57 40
 24]
[74 74 75 76 78 85 87 93 93 95]
[ 6 26 95 35 25 87 74 93 36 78 76 67  0 21 71 36 85 74 13 75 93 73 57 40
 24]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [13]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [1, 2, 3],
    [7, 8, 9],
    [4, 5, 6],
    [1, 2, 3]
])

unique = np.unique(arr, axis=0)
print(unique)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
