In [1]:
import numpy as np

In [5]:
a = np.array([1, 2, 3])
print(a)
print(a.ndim)  # Number of dimensions
print(a.shape) # Number of items per dimension
print(a.dtype) # Internal data type

[1 2 3]
1
(3,)
int32


In [9]:
b = np.array([1, 2, 3], dtype='int16')
print(b.dtype)
print(b.itemsize) # Bytes per item
print(b.size)     # Number of items
print(b.nbytes)   # Total memory taken

int16
2
3
6


In [12]:
c = np.array([[1, 2, 3], [4, 5, 6]])
print(c.shape)
print(c[0, 2]) # Use comma indexing, a-la-c#
print(c[0, -1]) # Negative indexing accepted
print(c[1, :])
print(c[:, 0]) # Can use slices in either index location

(2, 3)
3
3
[4 5 6]
[1 4]


In [14]:
d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(d)

d[:, 1] = -1 # Array is always properly shaped, this will assign to the entire column
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1 -1  3]
 [ 4 -1  6]
 [ 7 -1  9]]


-----

In [18]:
zeros = np.zeros((3, 4)) # Pass shape, as would be seen from arr.shape. Must be a tuple
print(zeros)

zeros = np.zeros((3, 4), dtype='int32') # Float seems to be assumed, specify int if desired
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [20]:
ones = np.ones((3, 3), dtype='int32')
print(ones)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [21]:
other = np.full((3, 3), 5) # Data type is taken from given value
print(other)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [23]:
fromOther = np.full_like(other, 10) # Copy shape from an existing array
print(fromOther)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [27]:
rand = np.random.rand(3, 4) # ! Shape isn't in a tuple, the dimensions are passed directly !
print(rand)

rand = np.random.random_sample(other.shape) # Copy shape from existing array
print(rand)

rand = np.random.randint(10, size=(3, 3)) # First arg is exclusive upper bound
print(rand)

rand = np.random.randint(-5, 5, size=(3, 3)) # Specify range of ints as first two args
print(rand)

[[0.94454838 0.61978553 0.98849193 0.54947219]
 [0.37755576 0.35040561 0.54133499 0.91594589]
 [0.64107319 0.69218347 0.31808207 0.85745347]]
[[0.83290591 0.06178131 0.31897183]
 [0.92577382 0.75387144 0.57397115]
 [0.72846687 0.94395503 0.11563493]]
[[6 1 3]
 [7 0 3]
 [8 6 0]]
[[ 1  1  2]
 [-5  3 -1]
 [ 2  4 -3]]


In [29]:
print(np.identity(5)) # Identity

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [36]:
print(a)
rep0 = np.repeat([a], 3, axis=0) # Repeat the given array some number of times
print(rep0)

# Each element at the given level (axis) is expanded into the next cells some number of times
rep1 = np.repeat([a], 3, axis=1)
print(rep1)

print(c)
rep2 = np.repeat([c], 2, axis=1)
# Base shape [
#   [
#     [1 2 3]
#     [4 5 6]
#   ]
# ]
# Expected [
#   [
#     [1 2 3] [1 2 3]
#     [4 5 6] [4 5 6]
#   ]
# ]
print(rep2)

# Right so basically
# [ a0:[ [1 2 3] ] ]
# [ [ a1:[1 2 3] ] ]
# [ [ [a2:1 2 3] ] ]

[1 2 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 2 2 2 3 3 3]]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [1 2 3]
  [4 5 6]
  [4 5 6]]]


In [46]:
# Given challenge: [
#   [1 1 1 1 1]
#   [1 0 0 0 1]
#   [1 0 9 0 1]
#   [1 0 0 0 1]
#   [1 1 1 1 1]
# ]

def layers(*nums):
    # Happy path - assuming always at least one arg
    l = len(nums)
    # Initial case
    # arr = np.full((l, l), nums[0]) Every number (layer) except the center is actually 2 rows/columns
    arr = np.full((l * 2 - 1, l * 2 - 1), nums[0])
    for i in range(1, l):
        # Start from the outside
        # arr[i:-1-i, i:-1-i] = nums[i] Exclusive upper bound
        arr[i:-i, i:-i] = nums[i]
    # Actually that might do it
    return arr

print(layers(1, 0, 9, 5))

[[1 1 1 1 1 1 1]
 [1 0 0 0 0 0 1]
 [1 0 9 9 9 0 1]
 [1 0 9 5 9 0 1]
 [1 0 9 9 9 0 1]
 [1 0 0 0 0 0 1]
 [1 1 1 1 1 1 1]]


In [48]:
# Given solution
output = np.ones((5, 5))
print(output)

z = np.zeros((3, 3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [49]:
a = np.array([1,2,3]).copy()
print(a)

[1 2 3]


-----

In [68]:
# Math operations are applied to each item individually
print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)
print(a ** 2)
print(np.sin(a))
print(a > 2)

[3 4 5]
[-1  0  1]
[2 4 6]
[0.5 1.  1.5]
[1 4 9]
[0.84147098 0.90929743 0.14112001]
[False False  True]


In [51]:
# Item-by-item operation between arrays
b = np.array([1,2,3])
print(a + b)

[2 4 6]


In [53]:
# Matrix operations
a = np.ones((2, 3))
b = np.full((3, 2), 2)
print(a)
print(b)

print(np.matmul(a, b))

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]


-----

In [57]:
# Statistics
a = np.array([[1,4,9],[3,5,7]])
print(a)

[[1 4 9]
 [3 5 7]]


In [59]:
print(np.min(a))
print(np.min(a, axis=0))
print(np.min(a, axis=1))

1
[1 4 7]
[1 3]


In [60]:
print(np.sum(a))
print(np.sum(a, axis=0))

29
[ 4  9 16]


In [62]:
a = np.array([[1,4,9],[3,5,7]])
print(a.shape)
print(a.reshape((6,)))

(2, 3)
[1 4 9 3 5 7]


In [66]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.vstack([a, b]))
c = np.vstack([a, a])
d = np.vstack([b, b])
print(np.hstack([c, c, d]))

[[1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3 4 5 6]
 [1 2 3 1 2 3 4 5 6]]


In [78]:
# filedata = np.genfromtxt('data.txt', delimiter=',')
# Integers become floats
# filedata.astype('int32')

a = np.array([1,2,3,4,5])
print(a[[1,3,4]])
print(a[a > 3])
print(np.any(a > 3))
print(np.all(a > 3))

# Bit operations per value
print(a > 2)
print((a > 2) & (a < 5))
print(a ^ a[::-1])

[2 4 5]
[4 5]
True
False
[False False  True  True  True]
[False False  True  True False]
[4 6 0 6 4]


In [87]:
# Quiz time
arr = np.array(range(1, 31)).reshape((6, 5))
print(arr)

# Access 11, 12, 16, 17
print(arr[2:4, 0:2])

# Access 2, 8, 14, 20
# Probably related to bit masking
# Cells where the column is one higher than the row
print(arr[[0,1,2,3], [1,2,3,4]]) # Solution given
# I think I was out-thinking myself
# I was too focused on a solution that would work for any size array

# Access 4, 5, 24, 25, 29, 30
# Based on how the boxes have been drawn I imagine numbers in the row come together
print(arr[[0, 4, 5], 3:5])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[[11 12]
 [16 17]]
[ 2  8 14 20]
[[ 4  5]
 [24 25]
 [29 30]]
